version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Europe/Kiev
  open-pull-requests-limit: 10
  versioning-strategy: increase
