# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "dev"
    default_labels:
      - "dependencies"
      - "dependabot"
    # ignored_updates:
    #   - match:
    #       dependency_name: "express"
    #       # The version_requirement specifies the versions to ignore.
    #       version_requirement: "^1.0.0"
    #   - match:
    #       # Wildcards match unlimited arbitrary characters (or none)
    #       dependency_name: "aws*"
    automerged_updates:
      - match:
          dependency_type: "development"
          # Supported dependency types: "development, all, production"
          update_type: "all"
          # Supported updates to automerge:
          # - "security:patch"
          #   SemVer patch update that fixes a known security vulnerability
          # - "semver:patch"
          #   SemVer patch update, e.g. > 1.x && 1.0.1 to 1.0.3
          # - "semver:minor"
          #   SemVer minor update, e.g. > 1.x && 2.1.4 to 2.3.1
          # - "in_range"
          #   matching the version requirement in your package manifest
          # - "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
